spring:
  profiles:
    default: local

springdoc:
  swagger-ui:
    path: /docs/swagger
    url: /docs/openapi3.yaml
    disable-swagger-default-url: true
    filter: true
    persist-authorization: true
    display-request-duration: true

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, environment
