spring:
  profiles:
    default: local

springdoc:
  swagger-ui:
    path: /docs/swagger
    url: /docs/openapi3.yaml
    disable-swagger-default-url: true
    filter: true
    persist-authorization: true
    display-request-duration: true
    default-model-expand-depth: 10
